"""Service package for the local Drivers Manager web app."""

from app.services.common import (
    TRIP_PRESETS,
    backup_current_workspace,
    build_participants_export_filename,
    cache_optimization_result,
    cache_selection_result,
    build_domain_state,
    clear_current_dataset_context,
    clear_current_group_context,
    clear_pickup_order_rules,
    clear_ride_together_rules,
    clear_destination,
    current_workspace_snapshot,
    current_workspace_key,
    delete_pickup_order_rule,
    delete_ride_together_rule,
    duplicate_last_trip,
    get_cached_optimization_result,
    get_cached_selection_result,
    get_current_dataset_context,
    get_destination,
    get_pickup_order_rules,
    get_ride_together_rules,
    get_workspace_backup,
    load_sample_dataset,
    mark_current_dataset_context_customized,
    resolve_location_input,
    restore_workspace_backup,
    restore_trip_history_entry,
    save_destination,
    save_pickup_order_rule,
    save_ride_together_rule,
    validate_ready_state,
)
from app.services.destinations import (
    apply_saved_destination,
    delete_saved_destination,
    list_saved_destinations,
    save_destination_favorite,
)
from app.services.groups import apply_group, delete_group, list_groups, save_group
from app.services.history import delete_trip_history_entry, get_trip_history_entry, list_trip_history, save_trip_history
from app.services.invites import (
    create_trip_invite,
    get_trip_invite,
    get_trip_invite_by_token,
    get_trip_response,
    get_trip_response_by_token,
    import_all_trip_responses,
    import_trip_response,
    load_invite_session_into_workspace,
    list_trip_invites,
    list_trip_responses,
    save_trip_response,
)
from app.services.participants import (
    delete_participant,
    export_participants_csv,
    get_participant,
    import_participants_csv,
    list_participants,
    reorder_participants,
    save_participant,
    set_participant_trip_active,
)
from app.services.meetup_spots import delete_meetup_spot, get_meetup_spot, list_saved_meetup_spots, save_meetup_spot
from app.services.planner import build_map_payload, run_driver_selection, run_optimization, run_sandbox_optimization
from app.services.settings import SOLVER_CATALOG, get_app_settings, save_app_settings, save_public_access_url, save_public_access_urls
from app.services.workspace import export_workspace_backup, import_workspace_backup


def clear_all_data() -> None:
    """Reset participant and destination state."""
    from app.services.participants import clear_all_data as clear_participants

    clear_participants()
    clear_destination()
    clear_current_dataset_context()
    clear_pickup_order_rules()
    clear_ride_together_rules()

__all__ = [
    "TRIP_PRESETS",
    "apply_group",
    "apply_saved_destination",
    "backup_current_workspace",
    "build_participants_export_filename",
    "cache_optimization_result",
    "cache_selection_result",
    "build_domain_state",
    "build_map_payload",
    "clear_all_data",
    "clear_current_dataset_context",
    "clear_current_group_context",
    "clear_pickup_order_rules",
    "clear_ride_together_rules",
    "current_workspace_snapshot",
    "current_workspace_key",
    "delete_pickup_order_rule",
    "delete_ride_together_rule",
    "delete_group",
    "delete_participant",
    "delete_saved_destination",
    "delete_trip_history_entry",
    "duplicate_last_trip",
    "export_participants_csv",
    "export_workspace_backup",
    "import_workspace_backup",
    "create_trip_invite",
    "get_cached_optimization_result",
    "get_cached_selection_result",
    "SOLVER_CATALOG",
    "get_app_settings",
    "get_current_dataset_context",
    "get_destination",
    "get_pickup_order_rules",
    "get_ride_together_rules",
    "get_participant",
    "get_trip_invite",
    "get_trip_invite_by_token",
    "get_trip_response",
    "get_trip_response_by_token",
    "get_trip_history_entry",
    "get_workspace_backup",
    "import_participants_csv",
    "import_all_trip_responses",
    "import_trip_response",
    "load_invite_session_into_workspace",
    "list_groups",
    "list_saved_meetup_spots",
    "list_participants",
    "list_saved_destinations",
    "list_trip_invites",
    "list_trip_responses",
    "list_trip_history",
    "load_sample_dataset",
    "mark_current_dataset_context_customized",
    "reorder_participants",
    "resolve_location_input",
    "restore_workspace_backup",
    "restore_trip_history_entry",
    "run_driver_selection",
    "run_optimization",
    "run_sandbox_optimization",
    "save_app_settings",
    "save_public_access_url",
    "save_public_access_urls",
    "save_destination",
    "save_pickup_order_rule",
    "save_ride_together_rule",
    "save_destination_favorite",
    "save_group",
    "save_meetup_spot",
    "save_participant",
    "save_trip_response",
    "set_participant_trip_active",
    "save_trip_history",
    "validate_ready_state",
    "delete_meetup_spot",
    "get_meetup_spot",
]
